#ifndef DEFAULTS_H
#define DEFAULTS_H

#define DEFAULT_DEVICE "default"
#define DEFAULT_BUFFER 16

#define DEFAULT_ADDR "::"
#define DEFAULT_PORT 1350
#define DEFAULT_FRAME 960
#define DEFAULT_JITTER 16

#define DEFAULT_RATE 48000
#define DEFAULT_CHANNELS 2
#define DEFAULT_BITRATE 128

#define DEFAULT_VERBOSE 1

#define DEFAULT_INSTANCES 1

#define DEFAULT_ADMIN_PORT 8377
#define DEFAULT_MAX_ADMIN 5
#define DEFAULT_COM_PORT 8378
#define DEFAULT_COM_BUFFSIZE 2048
#define DEFAULT_CLIENT_WAIT 0
#define DEFAULT_WAIT_LIST 5

#define DEFAULT_TIME_LEN 24
#define DEFAULT_LOGPATH "logs/"
#endif
